# Kubewarden Artifacthub Package config
#
# Use this config to submit the policy to https://artifacthub.io.
#
# This config can be saved to its default location with:
#   kwctl scaffold artifacthub > artifacthub-pkg.yml 
version: 0.0.1
name: enforce-prometheus-service-annotation-key
displayName: Enforce Prometheus Service Annotation Key
createdAt: 2024-12-12T12:51:21.849883885Z
description: "This Policy checks to see if Services have the specified Prometheus annotations like  `prometheus.io/scrape` and `filter.by.port.name`. These annotations are used to send metric data to your Prometheus instance. \n"
license: Apache-2.0
homeURL: https://github.com/kubewarden/rego-policies
containersImages:
- name: policy
  image: ghcr.io/kubewarden/policies/enforce-prometheus-service-annotation-key:v0.0.1
links:
- name: policy
  url: https://github.com/kubewarden/rego-policies/releases/download/v0.0.1/policy.wasm
- name: source
  url: https://github.com/kubewarden/rego-policies
install: |
  The policy can be obtained using [`kwctl`](https://github.com/kubewarden/kwctl):
  ```console
  kwctl pull ghcr.io/kubewarden/policies/enforce-prometheus-service-annotation-key:v0.0.1
  ```
  Then, generate the policy manifest and tune it to your liking. For example:
  ```console
  kwctl scaffold manifest -t ClusterAdmissionPolicy registry://ghcr.io/kubewarden/policies/enforce-prometheus-service-annotation-key:v0.0.1
  ```
maintainers:
- name: Kubewarden developers
  email: cncf-kubewarden-maintainers@lists.cncf.io
provider:
  name: kubewarden
recommendations:
- url: https://artifacthub.io/packages/helm/kubewarden/kubewarden-controller
annotations:
  kubewarden/mutation: 'false'
  kubewarden/resources: Service
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - services
      operations:
      - CREATE
      - UPDATE
