# Kubewarden Artifacthub Package config
#
# Use this config to submit the policy to https://artifacthub.io.
#
# This config can be saved to its default location with:
#   kwctl scaffold artifacthub > artifacthub-pkg.yml 
version: 0.0.1
name: prometheus-clusterrolebinding-has-incorrect-bindings
displayName: Prometheus Clusterrolebinding Has Incorrect Bindings
createdAt: 2024-12-12T12:50:47.456156761Z
description: "This Policy checks to see if the Prometheus Cluster Role Binding is bound to a `ClusterRole`, and is tied to a `ServiceAccount` name containing text of your choosing. The default policy is set for search for the Service Account name containing the word `prometheus`. \n"
license: Apache-2.0
homeURL: https://github.com/kubewarden/rego-policies
containersImages:
- name: policy
  image: ghcr.io/kubewarden/policies/prometheus-clusterrolebinding-has-incorrect-bindings:v0.0.1
keywords:
- pci-dss
- hipaa
- soc2-type1
links:
- name: policy
  url: https://github.com/kubewarden/rego-policies/releases/download/v0.0.1/policy.wasm
- name: source
  url: https://github.com/kubewarden/rego-policies
install: |
  The policy can be obtained using [`kwctl`](https://github.com/kubewarden/kwctl):
  ```console
  kwctl pull ghcr.io/kubewarden/policies/prometheus-clusterrolebinding-has-incorrect-bindings:v0.0.1
  ```
  Then, generate the policy manifest and tune it to your liking. For example:
  ```console
  kwctl scaffold manifest -t ClusterAdmissionPolicy registry://ghcr.io/kubewarden/policies/prometheus-clusterrolebinding-has-incorrect-bindings:v0.0.1
  ```
maintainers:
- name: Kubewarden developers
  email: cncf-kubewarden-maintainers@lists.cncf.io
provider:
  name: kubewarden
recommendations:
- url: https://artifacthub.io/packages/helm/kubewarden/kubewarden-controller
annotations:
  kubewarden/mutation: 'false'
  kubewarden/resources: ClusterRoleBinding
  kubewarden/rules: |
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - v1
      resources:
      - clusterrolebindings
      operations:
      - CREATE
      - UPDATE
